# Generated by Django 4.1 on 2023-08-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='传染病类型')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='政策类别')),
                ('file_name', models.CharField(max_length=100, verbose_name='政策文件名')),
                ('file_path', models.FileField(upload_to='policy_files/', verbose_name='政策文件路径')),
                ('number', models.CharField(max_length=100, verbose_name='文号')),
                ('country', models.CharField(max_length=100, verbose_name='所属国家')),
                ('department', models.CharField(max_length=100, verbose_name='发布部门')),
                ('year', models.IntegerField(verbose_name='发布年份')),
                ('publish_date', models.DateField(verbose_name='发布日期')),
                ('implementation_date', models.DateField(verbose_name='实施日期')),
                ('keywords', models.CharField(max_length=100, verbose_name='关键词')),
                ('timeliness', models.CharField(max_length=100, verbose_name='时效性')),
                ('effectiveness_level', models.CharField(max_length=100, verbose_name='效力级别')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('status', models.CharField(max_length=100, verbose_name='状态')),
                ('disease_types', models.ManyToManyField(to='policies.diseasetype', verbose_name='传染病类型列表')),
            ],
        ),
    ]
