# Generated by Django 4.1 on 2023-08-04 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='disease_types',
            field=models.ManyToManyField(blank=True, null=True, to='policies.diseasetype', verbose_name='传染病类型列表'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='effectiveness_level',
            field=models.CharField(blank=True, choices=[('法律', '法律'), ('行政法规', '行政法规'), ('检查法规', '检查法规'), ('司法解释', '司法解释'), ('部门规章', '部门规章'), ('军事法规规章', '军事法规规章'), ('党内法规制度', '党内法规制度'), ('团体规定', '团体规定'), ('行业规定', '行业规定'), ('其他', '其他')], max_length=100, null=True, verbose_name='效力级别'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='policy_files/', verbose_name='政策文件路径'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='implementation_date',
            field=models.DateField(blank=True, null=True, verbose_name='实施日期'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='timeliness',
            field=models.CharField(blank=True, choices=[('现行有效', '现行有效'), ('失效', '失效'), ('已被修改', '已被修改'), ('尚未失效', '尚未失效'), ('部分失效', '部分失效')], max_length=100, null=True, verbose_name='时效性'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='year',
            field=models.IntegerField(help_text='请输入发布年份 yyyy（有效年份为1949~当前年份）', validators=[django.core.validators.MinValueValidator(1949, message='年份不能早于1949年'), django.core.validators.MaxValueValidator(2023, message='年份不能晚于2023年')], verbose_name='发布年份'),
        ),
    ]
