# Generated by Django 4.1 on 2023-08-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_alter_policy_disease_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='disease_types',
            field=models.ManyToManyField(to='policies.diseasetype', verbose_name='传染病类型列表'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='file_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='政策文件名'),
        ),
    ]
