# Generated by Django 4.1 on 2023-08-06 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_remove_policy_status_policy_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPolicy',
            fields=[
            ],
            options={
                'verbose_name': '政策批量导入导出',
                'verbose_name_plural': '政策批量导入导出',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('policies.policy',),
        ),
        migrations.AlterModelOptions(
            name='diseasetype',
            options={'verbose_name': '传染病类型', 'verbose_name_plural': '传染病类型'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': '传染病防治政策查询及添加', 'verbose_name_plural': '传染病防治政策查询及添加'},
        ),
        migrations.AlterField(
            model_name='diseasetype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='year',
            field=models.IntegerField(default=1949, help_text='请输入发布年份 yyyy（有效年份为1949~当前年份）', validators=[django.core.validators.MinValueValidator(1949, message='年份不能早于1949年'), django.core.validators.MaxValueValidator(2023, message='年份不能晚于2023年')], verbose_name='发布年份'),
        ),
    ]
